### ISSUE TITLE
Terraform script for the deployment infrastructure

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Infrastructure#4]
To include replacing hand created k8s instances with automated. 

To run as a github (manual) action within the Infrastructure repo. 

Acceptance criteria:
- [ ] Prototype of triggering terraform via github action
- [x] Approach to use for management of state of the infrastructure + alignment of terraform scripts. 
- [ ] Document the setup and choices in the Deployment design document
- [x] automatically update the DNS record when terraforming a new environment
- [ ] Documented process for using the script for the setting up a new environment, clear what is automated + what is manual

**Comment by valentinyanakiev** [comment]
This looks more like an epic in the form of "Infrastructure-as-Code (IaC". We should break it down into actionable items, otherwise this will be blocking our board forever.
