### ISSUE TITLE
Configuration of the elastic service dashboards

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Infrastructure#67]
## Description
As a operations mgr, I want to be able to see what is happening with the Cherrytwist server / client when deployed

## Acceptance criteria

- [ ] Kibana account configured to have test & dev dashboards (Cherrytwist - Dev & Cherrytwist - Test)
   - [ ] Dashboards should aggregate data based on the environment field of the logs 
   - [ ] Different colours for different categories
      - [ ] Red for Error
      - [ ] Orange for Warning
      - [ ] Green for Verbose

**Comment by valentinyanakiev** [comment]
Updated AC.
