### ISSUE TITLE
Reduce token expiration time on Dev environment

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Infrastructure#71]
## Description
As a developer I want a fast test-debug loop for token refresh

## Acceptance criteria

- [ ] Dev enviornment should have tokens expiring after 5 minutes

**Comment by valentinyanakiev** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes

Can't be less than 10 minutes.
